server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3307/${DB_NAME:powerup}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:dev-secret}

appTitle: "Microservicio de Gestión de Restaurante, Arquitectura Hexagonal"
appDescription: "API para la creación y adminsitración de restaurante, platos y pedidos. Parte de la solución Power-up"
appVersion: "1.0.0"